# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: forbid-binary
  - id: script-must-have-extension
  - id: shellcheck

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-private-key
    exclude: ^functions/security/tls.sh$
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
minimum_pre_commit_version: '4'
